# Generated by Django 5.2.12 on 2026-03-24 12:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=150)),
                ('cnpj', models.CharField(blank=True, max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=80)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('limite_usuarios', models.PositiveIntegerField(blank=True, help_text='Deixe em branco para ilimitado.', null=True)),
                ('limite_ordens_mes', models.PositiveIntegerField(blank=True, help_text='Deixe em branco para ilimitado.', null=True)),
                ('limite_produtos', models.PositiveIntegerField(blank=True, help_text='Deixe em branco para ilimitado.', null=True)),
                ('periodo_teste_dias', models.PositiveIntegerField(default=7)),
                ('destaque', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('exibir_no_site', models.BooleanField(default=True)),
                ('descricao', models.TextField(blank=True)),
                ('recursos', models.TextField(blank=True, help_text='Um recurso por linha.')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['ordem', 'preco_mensal', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodape_nota', models.TextField(blank=True, default='Documento interno sem valor fiscal.')),
                ('cor_primaria', models.CharField(default='#1d4ed8', max_length=20)),
                ('logo_url', models.URLField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Configuração da empresa',
                'verbose_name_plural': 'Configurações das empresas',
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('TESTE', 'Período de teste'), ('ATRASADA', 'Pagamento pendente'), ('CANCELADA', 'Cancelada'), ('BLOQUEADA', 'Bloqueada')], default='TESTE', max_length=20)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('renovar_automaticamente', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='core.empresa')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='core.plano')),
                ('proximo_plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrades_agendados', to='core.plano')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('APROVADA', 'Aprovada'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='core.assinatura')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_plano', to='core.empresa')),
                ('plano_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_origem', to='core.plano')),
                ('plano_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_destino', to='core.plano')),
            ],
            options={
                'verbose_name': 'Solicitação de plano',
                'verbose_name_plural': 'Solicitações de plano',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='VinculoUsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('ADMIN', 'Administrador'), ('GERENTE', 'Gerente'), ('ATENDENTE', 'Atendente'), ('MECANICO', 'Operador')], default='ADMIN', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_vinculados', to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_empresariais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vínculo do usuário com empresa',
                'verbose_name_plural': 'Vínculos dos usuários com empresas',
                'unique_together': {('usuario', 'empresa')},
            },
        ),
    ]
