from django.urls import path
from .views import (
    blocked_subscription,
    billing_checkout,
    billing_status,
    billing_webhook,
    cancelar_assinatura_cliente,
    comecar_agora,
    dashboard,
    editar_empresa,
    equipe,
    excluir_vinculo,
    pagina_inicial,
    planos_empresa,
    selecionar_empresa,
    trocar_plano,
    atualizar_vinculo,
)
from .saas_admin import (
    aprovar_solicitacao_plano_saas,
    criar_empresa_saas,
    criar_plano_saas,
    editar_assinatura_saas,
    editar_empresa_saas,
    editar_plano_saas,
    painel_admin,
    recusar_solicitacao_plano_saas,
    saas_assinaturas,
    saas_empresas,
    saas_planos,
    saas_usuarios,
)

urlpatterns = [
    path('', pagina_inicial, name='home'),
    path('comecar/', comecar_agora, name='onboarding'),
    path('painel/', dashboard, name='dashboard'),
    path('planos/', planos_empresa, name='plans'),
    path('assinatura/cartao/', billing_checkout, name='billing_checkout'),
    path('assinatura/status/', billing_status, name='billing_status'),
    path('assinatura/cancelar/', cancelar_assinatura_cliente, name='cancel_subscription'),
    path('assinatura/bloqueada/', blocked_subscription, name='blocked_subscription'),
    path('assinatura/webhook/mercado-pago/', billing_webhook, name='billing_webhook'),
    path('assinatura/webhook/mercado-pago', billing_webhook, name='billing_webhook_no_slash'),
    path('planos/<int:plano_id>/trocar/', trocar_plano, name='change_plan'),
    path('equipe/', equipe, name='team'),
    path('equipe/<int:pk>/atualizar/', atualizar_vinculo, name='team_update'),
    path('equipe/<int:pk>/excluir/', excluir_vinculo, name='team_delete'),
    path('empresa/', editar_empresa, name='company_settings'),
    path('selecionar-empresa/', selecionar_empresa, name='selecionar_empresa'),
    path('painel-admin/', painel_admin, name='saas_admin_dashboard'),
    path('painel-admin/empresas/', saas_empresas, name='saas_admin_empresas'),
    path('painel-admin/empresas/nova/', criar_empresa_saas, name='saas_admin_empresa_create'),
    path('painel-admin/assinaturas/', saas_assinaturas, name='saas_admin_assinaturas'),
    path('painel-admin/usuarios/', saas_usuarios, name='saas_admin_usuarios'),
    path('painel-admin/planos/', saas_planos, name='saas_admin_planos'),
    path('painel-admin/planos/novo/', criar_plano_saas, name='saas_admin_plano_create'),
    path('painel-admin/empresas/<int:pk>/editar/', editar_empresa_saas, name='saas_admin_empresa_edit'),
    path('painel-admin/assinaturas/<int:pk>/editar/', editar_assinatura_saas, name='saas_admin_assinatura_edit'),
    path('painel-admin/planos/<int:pk>/editar/', editar_plano_saas, name='saas_admin_plano_edit'),
    path('painel-admin/solicitacoes/<int:pk>/aprovar/', aprovar_solicitacao_plano_saas, name='aprovar_solicitacao'),
    path('painel-admin/solicitacoes/<int:pk>/recusar/', recusar_solicitacao_plano_saas, name='recusar_solicitacao'),
]
