from django.urls import path
from .views import (
    adicionar_item_ordem_servico,
    criar_cliente,
    criar_ativo,
    criar_nota,
    criar_ordem_servico,
    detalhe_ordem_servico,
    editar_cliente,
    editar_item_ordem_servico,
    editar_ativo,
    editar_ordem_servico,
    excluir_cliente,
    excluir_item_ordem_servico,
    excluir_ativo,
    excluir_ordem_servico,
    imprimir_nota,
    imprimir_ordem_servico,
    lista_clientes,
    lista_ativos,
    lista_ordens_servico,
)

urlpatterns = [
    path('clientes/', lista_clientes, name='customer_list'),
    path('clientes/novo/', criar_cliente, name='customer_create'),
    path('clientes/<int:pk>/editar/', editar_cliente, name='customer_edit'),
    path('clientes/<int:pk>/excluir/', excluir_cliente, name='customer_delete'),
    path('ativos/', lista_ativos, name='asset_list'),
    path('ativos/novo/', criar_ativo, name='asset_create'),
    path('ativos/<int:pk>/editar/', editar_ativo, name='asset_edit'),
    path('ativos/<int:pk>/excluir/', excluir_ativo, name='asset_delete'),
    path('os/', lista_ordens_servico, name='service_order_list'),
    path('os/nova/', criar_ordem_servico, name='service_order_create'),
    path('os/<int:pk>/', detalhe_ordem_servico, name='service_order_detail'),
    path('os/<int:pk>/editar/', editar_ordem_servico, name='service_order_edit'),
    path('os/<int:pk>/excluir/', excluir_ordem_servico, name='service_order_delete'),
    path('os/<int:pk>/imprimir/', imprimir_ordem_servico, name='service_order_print'),
    path('os/<int:pk>/item/', adicionar_item_ordem_servico, name='service_order_add_item'),
    path('os/<int:pk>/item/<int:item_pk>/editar/', editar_item_ordem_servico, name='service_order_edit_item'),
    path('os/<int:pk>/item/<int:item_pk>/excluir/', excluir_item_ordem_servico, name='service_order_delete_item'),
    path('os/<int:pk>/nota/', criar_nota, name='invoice_create'),
    path('notas/<int:pk>/imprimir/', imprimir_nota, name='invoice_print'),
]
