# Generated by Django 5.2.12 on 2026-03-24 12:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
                ('placa', models.CharField(blank=True, max_length=10)),
                ('cor', models.CharField(blank=True, max_length=30)),
                ('km', models.PositiveIntegerField(default=0)),
                ('chassi', models.CharField(blank=True, max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativos', to='workshop.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativos', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('data_abertura', models.DateField()),
                ('previsao_entrega', models.DateField(blank=True, null=True)),
                ('queixa', models.TextField(verbose_name='Queixa do cliente')),
                ('diagnostico', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('valor_mao_de_obra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO', 'Aguardando produto'), ('FINALIZADA', 'Finalizada'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='core.empresa')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop.ativo')),
            ],
            options={
                'verbose_name': 'Ordem de serviço',
                'verbose_name_plural': 'Ordens de serviço',
                'ordering': ['-criado_em'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ItemOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('PRODUTO', 'Produto'), ('SERVICO', 'Serviço')], default='PRODUTO', max_length=10)),
                ('descricao', models.CharField(max_length=150)),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_ordem_servico', to='core.empresa')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.produto')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='workshop.ordemservico')),
            ],
            options={
                'verbose_name': 'Item da ordem de serviço',
                'verbose_name_plural': 'Itens da ordem de serviço',
            },
        ),
        migrations.CreateModel(
            name='NotaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(max_length=20)),
                ('data_emissao', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_internas', to='core.empresa')),
                ('ordem_servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_interna', to='workshop.ordemservico')),
            ],
            options={
                'verbose_name': 'Nota interna',
                'verbose_name_plural': 'Notas internas',
                'ordering': ['-criado_em'],
                'unique_together': {('empresa', 'numero_nota')},
            },
        ),
    ]
